Added condition to convert image to rgb only when it is rgb
ocampor/image-quality pull request #43
Opened 2022-01-12 21:51 UTC by njay225

When running `brisque.score()`, and error gets thrown:

> ValueError: the input array must have size 3 along channel_axis, got (80, 512)

The problem is that in the `calculate_features` function in `brisque.py`, two `Brisque` objects get created.

Within the constructor of the `Brique` class, the function `skimage.color.rgb2gray()` gets called.

Back to the `calculate_features` method, the first `Brique` object that gets called, the input image is RGB; however, the second `Brique` object that gets called is already in grayscale. The `skimage.color.rgb2gray()` function throws an error that the input is already in grayscale as it expects 3 channels.

The solution was to add a condition around the call to `skimage.color.rgb2gray()` within the `Brisque` class.

Replace line 45 of `imquality/brisque.py' with:

```
# Only convert image to grayscale if RGB
if self.image.shape[-1] == 3:
    self.image = skimage.color.rgb2gray(self.image)
```

2022-01-23 20:40 UTC, ocampor requested changes
Hey, thanks for your PR. Can we create some unit tests to maintain this functionality in the future?

2022-01-23 20:40 UTC, ocampor commented on imquality/brisque.py
> +        if self.image.shape[-1] == 3:
There are images with 4 channels. Do you think that we can generalize this solution to those too?

2022-02-03 12:47 UTC, HodeiG commented on imquality/brisque.py
> +        if self.image.shape[-1] == 3:
Hi, this is affecting us as well.

Regarding the images with 4 channels, that could be an issue as well, but the thing is that the call to `skimage.color.rgb2gray` will eventually check the same condition. See https://github.com/scikit-image/scikit-image/blob/61ddd88a9f1d68920bf85c0c6f37e5fe69c07c9f/skimage/color/colorconv.py#L137

Hence guarding this call with this condition makes sense.

2022-02-04 11:05 UTC, HodeiG commented on imquality/brisque.py
> +        if self.image.shape[-1] == 3:
@ocampor Thinking a bit more about this issue and the fact that you are using `rgb2gray` to convert an RGB image to Gray, it makes me think that somehow your code should be more explicit about using RGB images.

For instance, in https://github.com/ocampor/image-quality/blob/d548cdedb9e3779b553ff11e12cfcd28c4a5273f/imquality/brisque.py#L160 you could force the PIL image to be in RGB format:
`image = image.convert('RGB')`

Alternatively, you could raise an exception if the image is not an RGB so the user takes care of this, but this wouldn't be backwards compatible.

Anyways, enforcing the RGB format I believe you can always make sure that the image has 3 channels. There is more information regarding the PIL supported formats in here: https://pillow.readthedocs.io/en/stable/handbook/concepts.html

2022-02-08 16:44 UTC, ocampor commented on imquality/brisque.py
> +        if self.image.shape[-1] == 3:
@njay225 could you add the changes requested by @HodeiG ?

2022-02-12 06:59 UTC, merged